// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMybO-N0_QlhlECPaWP-V8CK2y25PMkO8',
    appId: '1:200570500940:web:44bcca01a7951dbdfa01e9',
    messagingSenderId: '200570500940',
    projectId: 'fintech-1f07e',
    authDomain: 'fintech-1f07e.firebaseapp.com',
    storageBucket: 'fintech-1f07e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuvCyTAihR8AQ8GYrGMLXM-qQCmVhMEhU',
    appId: '1:200570500940:android:7ea81d70b15cb79afa01e9',
    messagingSenderId: '200570500940',
    projectId: 'fintech-1f07e',
    storageBucket: 'fintech-1f07e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLZZ9J5KswgofZJ6YCEYCNu8TNOt8Lo4s',
    appId: '1:200570500940:ios:c03ccb9945d77b86fa01e9',
    messagingSenderId: '200570500940',
    projectId: 'fintech-1f07e',
    storageBucket: 'fintech-1f07e.firebasestorage.app',
    iosBundleId: 'com.example.fintechApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLZZ9J5KswgofZJ6YCEYCNu8TNOt8Lo4s',
    appId: '1:200570500940:ios:c03ccb9945d77b86fa01e9',
    messagingSenderId: '200570500940',
    projectId: 'fintech-1f07e',
    storageBucket: 'fintech-1f07e.firebasestorage.app',
    iosBundleId: 'com.example.fintechApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMybO-N0_QlhlECPaWP-V8CK2y25PMkO8',
    appId: '1:200570500940:web:0c3d168b43f1bc68fa01e9',
    messagingSenderId: '200570500940',
    projectId: 'fintech-1f07e',
    authDomain: 'fintech-1f07e.firebaseapp.com',
    storageBucket: 'fintech-1f07e.firebasestorage.app',
  );
}
