// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:fintech_app/features/home/data/models/coin_model.dart';
import 'package:fintech_app/features/home/data/models/global_data_response.dart';
import 'package:fintech_app/features/home/data/models/trending_response.dart';
import 'package:fintech_app/features/portfolio/data/models/user_holding_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(CoinDataAdapter());
    registerAdapter(CoinItemAdapter());
    registerAdapter(CoinModelAdapter());
    registerAdapter(CoinWrapperAdapter());
    registerAdapter(GlobalDataResponseAdapter());
    registerAdapter(GlobalMarketDataAdapter());
    registerAdapter(TrendingResponseAdapter());
    registerAdapter(UserHoldingModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(CoinDataAdapter());
    registerAdapter(CoinItemAdapter());
    registerAdapter(CoinModelAdapter());
    registerAdapter(CoinWrapperAdapter());
    registerAdapter(GlobalDataResponseAdapter());
    registerAdapter(GlobalMarketDataAdapter());
    registerAdapter(TrendingResponseAdapter());
    registerAdapter(UserHoldingModelAdapter());
  }
}
